// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgjynrlmquadiyuaedvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnanlucmxtcXVhZGl5dWFlZHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDIyMTUsImV4cCI6MjA2MzQ3ODIxNX0.KBFsOKPEShxIlcNZSM4CEB_Tdml1HDeddFfdqm6cHQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);